services:
  - type: web
    name: nubox-sync
    runtime: docker
    dockerfilePath: ./render-service/Dockerfile
    dockerContext: ./render-service
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUBOX_UTN
        sync: false
      - key: VERCEL_HISTORIAL_URL
        sync: false
      - key: SYNC_SECRET
        sync: false
