services:
  - type: web
    name: nubox-sync
    runtime: node
    rootDir: render-service
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUBOX_RUT
        sync: false
      - key: NUBOX_PASSWORD
        sync: false
      - key: BROWSERLESS_TOKEN
        sync: false
      - key: VERCEL_HISTORIAL_URL
        sync: false
      - key: SYNC_SECRET
        sync: false
